### ISSUE TITLE
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic

### ISSUE THREAD

**Issue by akatechis** [webpack-contrib/html-loader#113]
**I'm submitting a bug report**

**Webpack version:** 2.2.1

**HTML-Loader version:** 0.4.4

**Please tell us about your environment:**
Windows 10, running webpack in `Git Bash` terminal.

**Current behavior:**
Running webpack causes the following deprecation warning:
```
(node:20712) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (C:\workspace\app\node_modules\loader-utils\index.js:78:3)
    at getLoaderConfig (C:\workspace\app\node_modules\html-loader\index.js:17:26)
    at Object.module.exports (C:\workspace\app\node_modules\html-loader\index.js:28:15)
    at LOADER_EXECUTION (C:\workspace\app\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (C:\workspace\app\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (C:\workspace\app\node_modules\loader-runner\lib\LoaderRunner.js:229:2)
    at Array.<anonymous> (C:\workspace\app\node_modules\loader-runner\lib\LoaderRunner.js:202:4)
    at Storage.finished (C:\workspace\app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:15)
    at C:\workspace\app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:69:9
    at C:\workspace\app\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
```

**Expected/desired behavior:** I should not see the deprecation warning.

The relevant rule for html-loader is the following (I'm using this in a knockout app, which allows developers to use HTML comments for data-binding "virtual elements." I configure html-loader to leave those comments intact:
```
{
      test: /\.html$/,
      use: [{
        loader: "html-loader",
        options: {
          ignoreCustomFragments: [/<!--\s*\/?ko.*-->/] // ignore knockout comments used for bindings
        }
      }]
}
```

* **What is the motivation / use case for changing the behavior?**
The issue in the deprecation warning asks webpack users to file an issue with any loader that triggers this warning.
 
* **Browser:** all
 
* **Language:** My config file is written in ES6

**Comment by d3viant0ne** [comment]
@akatechis - We have seen & fixed this in other loaders thus far. PR is in, I'll get it merged & published shortly.

**Comment by d3viant0ne** [comment]
@akatechis - `html-loader v0.4.5` has been published to npm

**Comment by beckyao** [comment]
vim webpack.config.js

write "process.traceDeprecation = true" 

you will fix it
