### ISSUE TITLE
Comment Parsing with interpolate and minify=false

### ISSUE THREAD

**Issue by alexan** [webpack-contrib/html-loader#128]
**I'm submitting a bug report**

**Webpack version:**
3.0.0

**HTML-Loader version:**
0.4.5

**Please tell us about your environment:**
OSX 10.x / Windows 10

**Current behavior:**
when I'm using this configuration combination (mimimize:false, interpolate:true):
```
{
   loader: 'html-loader',
   options: {
      minimize: false,
      interpolate: true
   }
}
```
with an html file containing a complicated comment:
```
<!--
       _    _                _
      | |  | |              | |
      | |__| | ___  __ _  __| | ___ _ __
      |  __  |/ _ \/ _` |/ _` |/ _ \ '__|
      | |  | |  __/ (_| | (_| |  __/ |
      |_|  |_|\___|\__,_|\__,_|\___|_|

-->
```

I'm getting following error
```
Module build failed: Error: Line 5: Unexpected identifier
    at ErrorHandler.constructError (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:3396:22)
    at ErrorHandler.createError (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:3414:27)
    at JSXParser.Parser.unexpectedTokenError (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:542:39)
    at JSXParser.Parser.throwUnexpectedToken (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:552:21)
    at JSXParser.Parser.consumeSemicolon (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:845:23)
    at JSXParser.Parser.parseExpressionStatement (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:2080:15)
    at JSXParser.Parser.parseStatement (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:2495:35)
    at JSXParser.Parser.parseStatementListItem (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:1823:31)
    at JSXParser.Parser.parseProgram (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:3061:29)
    at Object.parse (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/esprima/dist/esprima.js:117:24)
    at Object.parse (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/recast/lib/parser.js:26:32)
    at compile (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/es6-templates/lib/index.js:41:20)
    at Object.module.exports (/Users/alexander.eder/Downloads/devpackMin-v2.0.11/workspace/playgroud/commentBug/node_modules/html-loader/index.js:123:13)
```
**Expected/desired behavior:**
the build should not throw an error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal**
https://gist.github.com/alexan/9b8d1682d0576dd13d5424d597b914a9

**Language:**
all

**Comment by michael-ciniawsky** [comment]
Closing in favor of #23

**Comment by artaommahe** [comment]
@alexan using `` ` `` in comment leads to this error
