### ISSUE TITLE
Shim webpack imports of HTML/CSS while in Mocha tests

### ISSUE THREAD

**Issue by pauleveritt** [webpack-contrib/html-loader#26]
I write my Angular applications as ES6 for WebPack, where one might do:

import SomeTemplate from "./template.html";
import "./some.css";

This works fine when combining Webpack and Babel, because Webpack affects the stream before Babel translates. But I also want to unit test my code, using Mocha and Babel. When I import the above, I get the two errors below.

It's to be expected, although I'm not sure why Babel by default interprets .html as React. Just wondering, what's the right way to shim this in tests? Do I need to write a plugin for my tests that intercepts imports of HTML and CSS and does nothing?

The HTML loading gives::

```
/Users/paul/projects/karl/admin5/src/admin/box/box.showlog.html:3
React.createElement(
^

ReferenceError: React is not defined
    at Object.<anonymous> (/Users/paul/projects/karl/admin5/src/admin/box/box.showlog.html:1:1)
    at Module._compile (module.js:430:26)
    at normalLoader (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/paul/projects/karl/admin5/src/admin/box/box.list.controller.js:1:14)
    at Module._compile (module.js:430:26)
    at normalLoader (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/paul/projects/karl/admin5/src/admin/box/tests/box.list.controller.specs.js:5:27)
    at Module._compile (module.js:430:26)
    at normalLoader (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/paul/projects/karl/admin5/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/paul/projects/karl/admin5/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/paul/projects/karl/admin5/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/paul/projects/karl/admin5/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:952:3
```

...and the CSS gives::

```
SyntaxError: /Users/paul/projects/karl/admin5/src/admin/admin.css: Unexpected token (2:11)
  1 | 
> 2 | md-sidenav a {
    |            ^
  3 |     text-decoration: none;
  4 | }
  5 | 
    at Parser.pp.raise (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.semicolon (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:69:81)
    at Parser.pp.parseExpressionStatement (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:427:8)
    at Parser.parseExpressionStatement (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:642:20)
    at Parser.pp.parseStatement (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:142:21)
    at Parser.parseStatement (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:621:22)
    at Parser.pp.parseTopLevel (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:30:21)
    at Parser.parse (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:70:17)
    at Object.parse (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/node_modules/babylon/lib/index.js:45:50)
    at Object.exports.default (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/helpers/parse.js:36:18)
    at File.parse (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:573:40)
    at File.parseCode (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:690:20)
    at /Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:167:12
    at File.wrap (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:638:16)
    at Pipeline.transform (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
    at Object.transformFileSync (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/node.js:137:37)
    at compile (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:132:20)
    at normalLoader (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/paul/projects/karl/admin5/src/admin/box/box.list.controller.js:1:14)
    at Module._compile (module.js:430:26)
    at normalLoader (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/paul/projects/karl/admin5/src/admin/box/tests/box.list.controller.specs.js:5:27)
    at Module._compile (module.js:430:26)
    at normalLoader (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/paul/projects/karl/admin5/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/paul/projects/karl/admin5/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/paul/projects/karl/admin5/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/paul/projects/karl/admin5/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/paul/projects/karl/admin5/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:952:3
```

**Comment by potapovDim** [comment]
var hook = require('css-modules-require-hook');
var sass = require('node-sass');
var path = require('path');

hook({
  extensions: ['.scss'],
  preprocessCss: function (scss, filepath) {
    var result =  sass.renderSync({
      data: scss,
      includePaths: [ path.resolve(filepath, '..') ]
    });

    return result.scss;
  }
});

**Comment by nagenderRawat** [comment]
I'am also having the same issue :(
